name: Building LunaOS ISO (Releases)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    permissions:
      contents: write

    container:
      image: archlinux:base-devel
      options: --privileged

    env:
      GPG_PASSPHRASE: ${{ secrets.PASSPHRASE }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

    steps:

      - name: Import GPG private key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ env.GPG_PRIVATE_KEY }}
          passphrase: ${{ env.GPG_PASSPHRASE }}
          trust_level: 5

      - name: Prepare container
        run: |
          pacman -Syuu --noconfirm --needed archiso xz zstd git gnupg zip
          
          # Chaotic-AUR and yours repository keys
          yes | pacman -Scc
          pacman-key --init
          pacman-key --recv-key 3056513887B78AEB 78B2BAAB82C8D511 --keyserver keyserver.ubuntu.com
          pacman-key --lsign-key 3056513887B78AEB 78B2BAAB82C8D511

          pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
          pacman -U --noconfirm 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
          
          pacman -U --noconfirm 'https://github.com/lenuma-inc/lunaos-repo/releases/download/lunaos-repo/lunaos-keyring-1-1-any.pkg.tar.zst'
          pacman -U --noconfirm 'https://github.com/lenuma-inc/lunaos-repo/releases/download/lunaos-repo/lunaos-mirrorlist-2-5-any.pkg.tar.zst'
          pacman-key --populate

          # Enable the multilib repository
          cat << EOM >> /etc/pacman.conf
          [multilib]
          Include = /etc/pacman.d/mirrorlist

          [lunaos-repo]
          Include = /etc/pacman.d/lunaos-mirrorlist
          SigLevel = Never

          [chaotic-aur]
          Include = /etc/pacman.d/chaotic-mirrorlist
          SigLevel = Never
          EOM

          pacman -Sy --noconfirm rate-mirrors

          rate-mirrors --allow-root arch | tee /etc/pacman.d/mirrorlist
          rate-mirrors --allow-root chaotic-aur | tee /etc/pacman.d/chaotic-mirrorlist

          yes | pacman -Scc

          pacman -Syyuu

          useradd -m -G wheel -s /bin/bash user && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user:user -R ..

      - name: Build LunaOS ISO
        run: |
          cd /__w/Weekly-ISO-Rebuilds
          git clone https://github.com/Lenuma-inc/LunaOS-ISO.git
          cd /__w/Weekly-ISO-Rebuilds/LunaOS-ISO
          sudo pacman -Sy
          sudo mkarchiso -v -w . -o build .

      - name: Generate checksum and sign ISO
        run: |
          cd /__w/Weekly-ISO-Rebuilds/LunaOS-ISO/build/
          sha256sum *.iso > SHA256SUMS
          gpg --pinentry-mode loopback --batch --yes --passphrase "$GPG_PASSPHRASE" --detach-sign --armor SHA256SUMS
          gpg --pinentry-mode loopback --batch --yes --passphrase "$GPG_PASSPHRASE" --detach-sign --armor *.iso

      - name: Checkout
        uses: actions/checkout@v3

      - name: Release ISO to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: /__w/Weekly-ISO-Rebuilds/LunaOS-ISO/build/
          server-dir: ${{ secrets.FTP_SERVER }}/public_html/ISO/
